// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlaylist.Server.Data;

namespace MusicPlaylist.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220202231900_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicPlaylist.Shared.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusicStyleId")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusicStyleId");

                    b.ToTable("Musics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumName = "Heaven and Hell",
                            GroupName = "Black Sabbath",
                            MusicStyleId = 1,
                            ReleaseYear = "1980",
                            SongName = "Heaven and Hell",
                            Url = "https://www.youtube.com/watch?v=RVUK2rtAkJE"
                        },
                        new
                        {
                            Id = 2,
                            AlbumName = "Ritchie Blackmore's Rainbow",
                            GroupName = "Rainbow",
                            MusicStyleId = 2,
                            ReleaseYear = "1975",
                            SongName = "Catch The Rainbow",
                            Url = "https://www.youtube.com/watch?v=V5QukAC-jqE"
                        },
                        new
                        {
                            Id = 3,
                            AlbumName = "What a wonderful world",
                            GroupName = "Louis Armstrong",
                            MusicStyleId = 3,
                            ReleaseYear = "1967",
                            SongName = "What a wonderful world",
                            Url = "https://www.youtube.com/watch?v=CWzrABouyeE"
                        });
                });

            modelBuilder.Entity("MusicPlaylist.Shared.MusicStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOfStyle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MusicStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOfStyle = "Heavy metal"
                        },
                        new
                        {
                            Id = 2,
                            NameOfStyle = "Rock 'n' Roll"
                        },
                        new
                        {
                            Id = 3,
                            NameOfStyle = "Jazz"
                        });
                });

            modelBuilder.Entity("MusicPlaylist.Shared.Music", b =>
                {
                    b.HasOne("MusicPlaylist.Shared.MusicStyle", "MusicStyle")
                        .WithMany()
                        .HasForeignKey("MusicStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicStyle");
                });
#pragma warning restore 612, 618
        }
    }
}
